### ISSUE TITLE
Provide an example for String matching conditional statement

### ISSUE THREAD

**Issue by nisan-tagar** [seanpmaxwell/Trool#12]
Thanks @seanpmaxwell for building this **cool trool tool** for the community!

Could you please share if String matching conditionals on the fact attributes are supported and if so, provide an example?
I want to use standard JS String matching methods such as contains(), match(), includes() etc ...

For example, say I have a transaction record with a description field, I would like to have a rule such that if the description contains a substring then evaluate to true.

Thanks in advance!

**Comment by seanpmaxwell** [comment]
This is not currently a supported feature. However, now that I'm thinking it about maybe I should implement being able to use a custom method that returns a boolean instead of just a simple comparison operator. So you could do something like `nameIncludes($param)` where `nameIncludes` would be a method you would have to implement on the Visitor's fact.

**Comment by nisan-tagar** [comment]
Yes that would be great. 
Please consider supporting the standard JS methods that are available on the attribute that is being referenced so for example on a JS String you could do:
$param.match("some_regex_expression")
Or:
$param.includes("some_substring")

This will allow creating complex business rules that are not possible with the basic operators.
This approach will also decouple the code from the rule definitions which is kind of the whole point of a rule engine.

**Comment by seanpmaxwell** [comment]
@nisan-tagar okay I implemented the feature. See Version 3.0.2. There's an example here https://github.com/seanpmaxwell/Trool/tree/master/test/NightClubRules. I decided to just allow a Fact function to be called. Allowing javascript string functions like `.matches` could get tricky because people often want to chain functions like `.lowerCase().matches()` first. That could cause spreadsheets to get messy. 

In return for implementing this feature could you do me a huge favor and consider trying out jet-schema (https://www.npmjs.com/package/jet-schema) if any of your current projects are using a schema-validation library.

**Comment by nisan-tagar** [comment]
Thanks @seanpmaxwell! Will definitely look into it.
